### ISSUE TITLE
no matches found

### ISSUE THREAD

**Issue by Oleg-Chashko** [wynioux/macOS-GateKeeper-Helper#12]
<img width="341" alt="Screenshot 2020-07-15 at 12 08 19" src="https://user-images.githubusercontent.com/62497891/87532778-ebfdea80-c693-11ea-9296-0e29d8ace6a3.png">

You have done a great job, completely rewritten the script! Thank.
It seems to me: Option №6 does not work (bug Screenshot). And the terminal window is freezes.

P.S.: I will convert your script to

[GateKeeper_Helper_v.1.2.0.zip](https://github.com/wynioux/macOS-GateKeeper-Helper/files/4924414/GateKeeper_Helper_v.1.2.0.zip)

For easy launch in terminal without:
To open helper for first time, right click on it then click open.
Or type via Terminal:
chmod + x GateKeeper_Helper.command

If you want, for convenience, you can also do. 
Thanks again.

**Comment by wynioux** [comment]
Even if you convert script, downloaders need to right click and then open. Because gatekeeper shows unidentified developer error.

**Comment by wynioux** [comment]
Should be work with changes.
