### ISSUE TITLE
macOS-GateKeeper-Helper its Zsh session, creates a hidden file ".zsh_history"

### ISSUE THREAD

**Issue by Oleg-Chashko** [wynioux/macOS-GateKeeper-Helper#18]
macOS-GateKeeper-Helper its Zsh session, creates a hidden file ".zsh_history"
<img width="719" alt="Bildschirmfoto 2020-08-23 um 14 06 24" src="https://user-images.githubusercontent.com/62497891/90978129-a44c6780-e54b-11ea-93c0-654d0a653cb8.png">
[(.zsh_history).zip](https://github.com/wynioux/macOS-GateKeeper-Helper/files/5113922/zsh_history.zip)
I would like the "ZSH Shell history" file not to be created. 

<img width="523" alt="Bildschirmfoto 2020-09-02 um 14 04 42" src="https://user-images.githubusercontent.com/62497891/91979823-a15d2e00-ed26-11ea-8e34-955b734113b9.png">

P.S.
I wanted the programs not to create log and history files. Without the knowledge of the user. I know this is creating the "ZSH Shell" session, not your script. But I would like the "ZSH Shell" session not to create this file.

**Comment by wynioux** [comment]
Actually, the .zsh_history file is generated automatically every time zsh is used. When the script is done, I rearrange it to delete this file.

**Comment by Oleg-Chashko** [comment]
@wynioux 
Hi, is it possible to make the script delete the hidden file ".zsh_history" and files folder ".zsh_sessions" on startup or exit?

Can you do the item: 6. Clear history and exit.?
sudo rm -f ~/.zsh_history
sudo rm -fdr ~/.zsh_sessions

Thank you for your script.

<img width="686" alt="Bildschirmfoto 2020-10-01 um 10 06 08" src="https://user-images.githubusercontent.com/62497891/94785752-622b0700-03d0-11eb-98ae-577763c407a3.png">

Links to sites "How to clear history in zsh":
https://unix.stackexchange.com/questions/544373/how-to-clear-history-in-zsh
https://til.hashrocket.com/posts/zn87awopb4-delete-a-command-from-zsh-history-
https://www.jamf.com/jamf-nation/discussions/35746/unify-your-macos-terminal-command-history
https://thorsten-hans.com/how-to-clean-zsh-history-temporary
https://stackoverflow.com/questions/22771958/delete-specific-line-from-oh-my-zsh-history

**Comment by Oleg-Chashko** [comment]
I did what I wanted. Please do better. You are a programmer you have more knowledge. Thanks.
[macOS-GateKeeper-Helper.zip](https://github.com/wynioux/macOS-GateKeeper-Helper/files/5310862/macOS-GateKeeper-Helper.zip)

You’ve probably noticed how the useless Terminal window remains after it’s completed. You can fix this?

I use "killall Terminal" or "pkill -a Terminal" to make the Terminal app close itself from within a script, but that will close every open Terminal window, so it’s not ideal.

**Comment by gradyen** [comment]
The problem here may be that the user is using different programs in the terminal at the same time. Force shutdown of the terminal may not be a good solution as it will interrupt other programs. Also, maybe you don't care about zsh history, but it seems to me that it's not a good idea to delete the history of people who care about zsh history.

**Comment by gradyen** [comment]
> The problem here may be that the user is using different programs in the terminal at the same time. Force shutdown of the terminal may not be a good solution as it will interrupt other programs. Also, maybe you don't care about zsh history, but it seems to me that it's not a good idea to delete the history of people who care about zsh history.

Sorry it is my project account. I accidentally comment from this account.

**Comment by Oleg-Chashko** [comment]
Thanks for the answer, I get it. I close the topic.
