### ISSUE TITLE
To check XProtect for it's state

### ISSUE THREAD

**Issue by JodhwaniMadhur** [wynioux/macOS-GateKeeper-Helper#20]
Hello Sir, I checked your Gatekeeper repository and it is absolutely fantastic, I just came to know about XProtect and that it is a part of XProtect and I am working on checking status of XProtect so do you have any idea on how to check if XProtect is running or not or does it have any API exposed to connect to it? And does disabling the GateKeeper also disable the XProtect?

**Comment by wynioux** [comment]
All the commands I wrote in the script were already available on the internet and I just wanted to collect them all in one place. Sorry, I don't know anything about XProtect.
