### ISSUE TITLE
When appearance is light, the font is poorly visible.

### ISSUE THREAD

**Issue by Oleg-Chashko** [wynioux/macOS-GateKeeper-Helper#7]
When the light theme is enabled, the yellow font is hard to see. It is advisable to change to a different color.
<img width="569" alt="Screenshot 2020-07-12 at 18 37 17" src="https://user-images.githubusercontent.com/62497891/87252068-a31a1c00-c470-11ea-926d-d6e17bf4a181.png">

**Comment by wynioux** [comment]
You are right. I think everyone uses dark mode :) It's my mistake. I will looking into it.
