### ISSUE TITLE
Bug: No such file with "drag and drop"

### ISSUE THREAD

**Issue by Oleg-Chashko** [wynioux/macOS-GateKeeper-Helper#8]
Bug with "drag and drop" in:
4) Remove app from Gatekeeper quarantine
5) Self-sign the app

### With "drag and drop" input does not work.
**Problem: extra oblique strokes and a space after the application name.**

<img width="671" alt="drag and drop" src="https://user-images.githubusercontent.com/62497891/87253318-9ac6de80-c47a-11ea-9b09-faaac1fcd242.png">

### With manual entry it works.

<img width="639" alt="Manual input" src="https://user-images.githubusercontent.com/62497891/87253330-a4e8dd00-c47a-11ea-81a6-7d8547fdd516.png">

**Comment by wynioux** [comment]
I'm looking the issue. Are you using zsh? Script written for bash, so it may be causing issue.

**Comment by Oleg-Chashko** [comment]
> I'm looking the issue. Are you using zsh? Script written for bash, so it may be causing issue.

In 2019, macOS Catalina adopted Zsh as the default login shell, replacing the aging GPLv2 licensed version of Bash, and when Bash is run interactively on Catalina, a warning is shown by default.
[https://support.apple.com/en-us/HT208050](url)

**Comment by wynioux** [comment]
Thank you for warning @Oleg-Chashko. I will rewrite entire script tonight.
